version: "3"
services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.11.1
    container_name: elasticsearch
    environment:
      - "discovery.type=single-node"
      - "ES_JAVA_OPTS=-Xms1G -Xmx1G"
    ports:
      - 9200:9200

  kibana:
    image: docker.elastic.co/kibana/kibana:7.11.1
    container_name: kibana
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch

  python-application:
    build: ./
    image: python-application:latest
    container_name: python-application
    environment:
      ES_HOST: elasticsearch
      ES_PORT: 9200
    depends_on:
      - elasticsearch
